__pycache__/_version.cpython-311.pyc,,
_version.py,sha256=4dXebS3MmuJVzRzthWNVLSC2f7ozQPniKxTATW5ZukM,413
pyzotero-1.5.18.dist-info/AUTHORS,sha256=ZMicxg7lRScOYbxzMPznlzMbmrFIUIHwg-NvljEMbRQ,110
pyzotero-1.5.18.dist-info/INSTALLER,sha256=zuuue4knoyJ-UwPPXg8fezS7VCrXJQrAP7zeNuwvFQg,4
pyzotero-1.5.18.dist-info/METADATA,sha256=0b7AJQJ5dFiYpERVv18Q92Nxdhh8bECDVY0HpMFRQ7E,6570
pyzotero-1.5.18.dist-info/RECORD,,
pyzotero-1.5.18.dist-info/REQUESTED,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
pyzotero-1.5.18.dist-info/WHEEL,sha256=yQN5g4mg4AybRjkgi-9yy4iQEFibGQmlz78Pik5Or-A,92
pyzotero-1.5.18.dist-info/top_level.txt,sha256=BOPNkPk5VtNDCy_li7Xftx6k0zG8STGxh-KgckcxLEw,18
pyzotero/__init__.py,sha256=5QI4Jou9L-YJAf_oN9TgRXVKgt_Unc39oADo2Ch8bLI,243
pyzotero/__pycache__/__init__.cpython-311.pyc,,
pyzotero/__pycache__/zotero.cpython-311.pyc,,
pyzotero/__pycache__/zotero_errors.cpython-311.pyc,,
pyzotero/zotero.py,sha256=2LxkzHXYUDZqsGdIsxzzqvTMhydh8xKNhcpt9MIi5xE,75878
pyzotero/zotero_errors.py,sha256=XzjUxKDQUMpRDBEQGTJ-wna0-bVoKIKK7AEDfKgzdfE,3664
